---
- name: Ajout clé GPG Wazuh
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Ajout repository Wazuh
  apt_repository:
    repo: deb https://packages.wazuh.com/4.x/apt/ stable main
    state: present
    filename: wazuh

- name: Installation Wazuh Manager
  apt:
    name: wazuh-manager
    state: present
    update_cache: yes

- name: Démarrage et activation Wazuh Manager
  service:
    name: wazuh-manager
    state: started
    enabled: yes

- name: Installation Filebeat
  apt:
    name: filebeat
    state: present

- name: Démarrage Filebeat
  service:
    name: filebeat
    state: started
    enabled: yes
